##### BASIC #####
set -g default-terminal "screen-256color"
set -g terminal-overrides ",xterm-256color:Tc"
set -g mouse on
set -g history-limit 10000
set -g escape-time 10

##### PREFIX (mobile friendly) #####
set -g prefix C-a
unbind C-b
bind C-a send-prefix

##### SPLIT #####
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

##### INDEX #####
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

##### STATUS BAR BASE #####
set -g status on
set -g status-position top
set -g status-interval 5
set -g status-justify left
set -g status-style "bg=#1e1e2e,fg=#cdd6f4"

##### ===== HIDE WINDOW STATUS ===== #####
set -g window-status-format ""
set -g window-status-current-format ""
set -g status-left-length 60
set -g status-right-length 80

##### ===== STATUS LEFT : USER ===== #####
set -g status-left "\
#[bg=#1e1e2e,fg=#f9e2af]\
#[bg=#f9e2af,fg=#1e1e2e,bold]  \
#[bg=#313244,fg=#cdd6f4] Finn \
#[bg=#1e1e2e,fg=#313244] "

##### ===== STATUS RIGHT : DAY & DATE ===== #####
set -g status-right "\
#[bg=#1e1e2e,fg=#a6e3a1]\
#[bg=#a6e3a1,fg=#1e1e2e,bold]  \
#[bg=#313244,fg=#cdd6f4] %a \
#[bg=#1e1e2e,fg=#313244] \
#[bg=#1e1e2e,fg=#f9e2af]\
#[bg=#f9e2af,fg=#1e1e2e,bold]  \
#[bg=#313244,fg=#cdd6f4] %d %b \
#[bg=#1e1e2e,fg=#313244]"

##### PANE STYLE #####
set -g pane-border-style "fg=#45475a"
set -g pane-active-border-style "fg=#89b4fa"

##### MESSAGE STYLE #####
set -g message-style "bg=#1e1e2e,fg=#cdd6f4"
